### ISSUE TITLE
Actualizar sitio web

### ISSUE THREAD

**Issue by cmaureir** [python-chile/pythonchile_v2#2]
Hola @cavb !
hace un tiempo pregunté en el grupo de telegram para actualizar la pagina pythonchile.cl
Miré de hacerme un usuario pero no funcionó.
Es tuyo el servidor donde actualmente está hosteado el sitio?
Vi que Pablo es el dueño del dominio, pero no sé si el tiene el tema en dreamhost, o tu.
Ojalá podamos volver a darle más movimiento :tada:
Gracias!

**Comment by cavb1205** [comment]
Hola Cristián

No el servidor no es mío, solo hago parte del grupo pero hasta el momento no he aportado nada.





Enviado desde mi smartphone Samsung Galaxy.



-------- Mensaje original --------
De: Cristián Maureira-Fredes <notifications@github.com>
Fecha: 8/7/20 03:43 (GMT-04:00)
A: python-chile/pythonchile_v2 <pythonchile_v2@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [python-chile/pythonchile_v2] Actualizar sitio web (#2)


Hola @cavb<https://github.com/cavb> !
hace un tiempo pregunté en el grupo de telegram para actualizar la pagina pythonchile.cl
Miré de hacerme un usuario pero no funcionó.
Es tuyo el servidor donde actualmente está hosteado el sitio?
Vi que Pablo es el dueño del dominio, pero no sé si el tiene el tema en dreamhost, o tu.
Ojalá podamos volver a darle más movimiento 🎉
Gracias!

**Comment by cmaureir** [comment]
Gracias @cavb1205,
@cavb como tu hiciste algunos cambios, los merge hacen deployment automatico al sitio?
La interfaz administrativa quien la administra para poder hacer un ping por acá?

**Comment by cavb** [comment]
Hola @cmaureir! Lo conversamos por telegram pero lo dejo aquí para que quede publico.
No tenemos aun deploys automáticos, sería genial implementarlo. Por el momento se corre un script en el server para hacer el pull del repo.
Acerca de la interfaz administrativa, estamos usando Wagtail CMS, asique para modificarla habria que meterle mano a su config. Aqui dejo la documentacion de [Wagtail](https://docs.wagtail.io/en/stable/)

**Comment by cmaureir** [comment]
Yo creo que ya hemos hecho bastante, y podríamos considerar el sitio "actualizado" jajaja
